using UnityEngine;
using UnityEditor;

namespace UnityTools.EditorTools {

#if UNITY_EDITOR
    public class BuiltInIcons
    {
        public static GUIContent GetIcon (string name, string tooltip) {
            return new GUIContent(EditorGUIUtility.IconContent(name, tooltip).image, tooltip);
		}

        public static readonly string[] allIcons = new string[] {
            
            "ClothInspector.PaintValue",
            "ClothInspector.ViewValue",
            "ClothInspector.SettingsTool",
            "ClothInspector.PaintTool",
            "ClothInspector.SelectTool",
            
            "TerrainInspector.TerrainToolSettings",
            "TerrainInspector.TerrainToolPlants",
            "TerrainInspector.TerrainToolTrees",
            "TerrainInspector.TerrainToolSplat",
            "TerrainInspector.TerrainToolSmoothHeight",
            "TerrainInspector.TerrainToolSetHeight",
            "TerrainInspector.TerrainToolRaise",
            
            "TreeEditor.Refresh",
            "TreeEditor.Trash",
            "TreeEditor.AddBranches",
            "TreeEditor.AddLeaves",
            "TreeEditor.Duplicate",
            "TreeEditor.BranchTranslate",
            "TreeEditor.BranchRotate",
            "TreeEditor.BranchFreeHand",
            "TreeEditor.BranchTranslate On",
            "TreeEditor.BranchRotate On",
            "TreeEditor.BranchFreeHand On",
            "TreeEditor.LeafTranslate",
            "TreeEditor.LeafRotate",
            "TreeEditor.LeafTranslate On",
            "TreeEditor.LeafRotate On",
            "Animation.AddEvent",
            "Animation.AddKeyframe",
            "Animation.NextKey",
            "Animation.PrevKey",
            "Animation.Record",
            "Animation.Play",
            "Animation.EventMarker",

            "WaitSpin00",
            "WaitSpin01",
            "WaitSpin02",
            "WaitSpin03",
            "WaitSpin04",
            "WaitSpin05",
            "WaitSpin06",
            "WaitSpin07",
            "WaitSpin08",
            "WaitSpin09",
            "WaitSpin10",
            "WaitSpin11",
            "lightMeter/redLight",
            "lightMeter/orangeLight",
            "lightMeter/lightRim",
            "lightMeter/greenLight",
            "PlayButtonProfile On",
            "PlayButton On",
            "PlayButtonProfile",
            "PlayButton",
            
            "_Help",
            "ScriptableObject Icon",
            "Clipboard",
            "animationvisibilitytoggleoff",
            "animationvisibilitytoggleon",
            "tree_icon",
            "tree_icon_leaf",
            "tree_icon_frond",
            "tree_icon_branch",
            "tree_icon_branch_frond",
            "editicon.sml",
            "Mirror",
            "SpeedScale",
            "Toolbar Minus",
            "Toolbar Plus More",
            "Toolbar Plus",
            "AnimatorController Icon",
            "TextAsset Icon",
            "Shader Icon",
            "cs Script Icon",
            "Profiler.NextFrame",
            "Profiler.PrevFrame",
            "ColorPicker.CycleSlider",
            "ColorPicker.CycleColor",
            "EyeDropper.Large",
            "AboutWindow.MainHeader",
            "StepButton On",
            "PauseButton On",
            "StepButton",
            "PauseButton",
            "ViewToolOrbit On",
            "ViewToolZoom On",
            "ViewToolMove On",
            "ViewToolOrbit",
            "ViewToolZoom",
            "ViewToolMove",
            "ScaleTool On",
            "RotateTool On",
            "MoveTool On",
            "ScaleTool",
            "RotateTool",
            "MoveTool",
            "Icon Dropdown",
            "Avatar Icon",
            "AvatarPivot",

            "SceneviewLighting",
            "MeshRenderer Icon",
            "Terrain Icon",
            "SettingsIcon",
            "Camera Icon",
            "PreMatLight1",
            "PreMatTorus",
            "PreMatCylinder",
            "PreMatLight0",
            "PreMatCube",
            "PreMatSphere",
            "PreTextureMipMapHigh",
            "PreTextureMipMapLow",
            "PreTextureRGB",
            "PreTextureAlpha",
            "PrefabModel Icon",
            "Prefab Icon",
            "VerticalSplit",
            "HorizontalSplit",
            "GameObject Icon",

            "TextField",
            "dockarea back",
            "Toolbar",
            "gameviewbackground",
            "AssetLabelIcon",
            "PB-BottomBarBg",
            "btn act",
            "console.infoicon",
            "scroll vert down",
            "toggle on",
            "cmd right",
            "cn entrybackodd",
            "ProjectBrowserTextureIconDropShadow",
            
            "console.warnicon.sml",
            "toggle",
            "ConsoleCountBadge",
            "IN Title Normal",
            "tabbar on",
            "ColorField",
            "cmd left",
            "IN foldout on",
            "IN foldout",
            "OL title",
            "scroll vert up",
            "CN Box",
            "Pre toolbar",
            "IN Title On Normal",
            "console.erroricon.sml",
            "slider horiz",
            "IN BigTitle",
            "toolbar button act",
            "ArrowNavigationRight",
            "ProfilerBadge",
            "btn",
            "cmd left on",
            "selected",
            "WindowBottomResize",

            "scroll vert",
            "slider thumb",

            "scroll vert thumb",
            "btn left",
            "cnentrybackeven",
            "Pre button",
            "console.erroricon",
            "dropwell predrop",
            "mini btn act",
            "OL box",
            "console.warnicon",
            "btn left on",
            "pane options",
            "helpbox",
            "progress back",
            "icon dropdown",
            "tabbar on f",
            "Inlined TextField Focus",
            "d_tranp",
            "dropwell nothumb focus",
            "PB-TopBarBg",
            "IN LockButton",
            "toolbar back",
            "dockarea overlay",
            "cmd mid on",
            "progress front",
            "dropwell nothumb",
            "console.infoicon.sml",
            
            "ProfilerPaneSublabel",
            "toolbar button",
            "transparent",
            "toolbar button on",
            "cmd left act",
            "window back",
            "btn right",

            "winbtn_mac_close_h",
            "winbtn_mac_close",
            "winbtn_mac_max",
            "winbtn_mac_inact",
            "winbtn_mac_min",

            "unselected",
            "cmd mid",
            "ProjectBrowserIconAreaBg",
            "white",
            "cmd",
            "mini btn",
            "toolbar button act@2x",
            "transparent@2x",
            "CollabNew",
            "dropwell nothumb@2x",
            "curvekeyframeweighted",
            "progress front@2x",
            "curvekeyframe",
            "selected@2x",
            
            "toggle@2x",
            "PrefabOverlayAdded Icon",
            
            "DefaultSorting",
            "scroll vert up@2x",
            "scroll vert thumb@2x",
            "FilterByType",
            "dropwell nothumb focus@2x",
            "LookDevClose@2x",
            "UnityEditor.SceneView",
            "Preset.Context",
            "cmd left@2x",
            "btn left@2x",
            "OL box@2x",
            "CN Box@2x",
            "console.erroricon.inactive.sml",
            "ToolHandlePivot",
            "Toolbar@2x",
            "toolbar button on@2x",
            "OL title@2x",
            "WindowBottomResize@2x",
            "btn left on@2x",
            "MoveTool on",
            "TextField@2x",
            "toggle on@2x",
            "Inlined TextField Focus@2x",
            "btn@2x",

            "console.warnicon.inactive.sml",
            "dropwell predrop@2x",
            "helpbox@2x",
            "Pre button@2x",
            "cnentrybackeven@2x",
            "btn right@2x",
            "dockarea overlay@2x",
            "renderdoc",
            
            "Project",
            "progress back@2x",
            "cn entrybackodd@2x",
            "gameviewbackground@2x",
            "curvekeyframesemiselectedoverlay",
            "slider thumb@2x",
            "IN foldout on@2x",
            "SceneViewFx",
            "FilterByLabel",
            "ConsoleCountBadge@2x",
            "ColorField@2x",
            "UnityEditor.ProfilerWindow",
            
            "toolbar pulldown@2x",
            "pulldown@2x",
            "GV gizmo pulldown@2x",
            "mini pulldown",
            "pulldown",
            "GV gizmo pulldown",
            "toolbar pulldown",
            "mini pulldown@2x",
            
            

            "toolbar back@2x",
            "tabbar on f@2x",
            
            "cmd mid on@2x",
            "AssetLabelIcon@2x",
            "btn act@2x",
            "UnityEditor.GameView",
            "DirectionalLight Icon",
            "unselected@2x",
            "UnityEditor.ConsoleWindow",
            "UnityEditor.AnimationWindow",
            "mini btn@2x",
            "UnityEditor.SceneHierarchyWindow",
            "mini btn act@2x",
            "cmd left on@2x",
            "IN foldout@2x",
            "DefaultAsset Icon",

            "toolbarsearchCancelButtonOff@2x",
            "toolbarsearch@2x",
            "Search Icon",
            "toolbarsearch",
            "toolbarsearchCancelButtonOff",
            "toolbarsearchpopup@2x",
            "toolbarsearchpopup",

            "PopupWindowOff@2x",
            "_Popup",
            "mini popup",
            "mini popup focus",
            "toolbar popup",
            "PopupWindowOff",
            "toolbar popup@2x",
            "mini popup@2x",
            "mini popup focus@2x",
            
            
            
            "SceneLoadIn",
            "slider horiz@2x",
            "toolbar button@2x",
            "PrefabOverlayRemoved Icon",
            "ToolHandleLocal",
            "RectTool",
            "scroll vert down@2x",
            "dockarea back@2x",
            "SceneLoadOut",
            "IN BigTitle@2x",
            "Main Light Gizmo",
            "ProfilerBadge@2x",
            "ToolHandleGlobal",
            "TransformTool On",
            "scroll vert@2x",
            "cmd@2x",
            "curvekeyframeselectedoverlay",
            "Asset Store",
            "FolderFavorite Icon",
            "tab_prev@2x",
            "Pre toolbar@2x",
            "Folder Icon",
            "CustomSorting",
            "SceneViewLighting",
            "UnityEditor.Graphs.AnimatorControllerTool",
            "Transform Icon",
            "IN LockButton@2x",
            "PackageBadgeNew",

            "Profiler.Audio",
            "preAudioPlayOn",
            "preAudioPlayOff",
            "SceneviewAudio",
            "preAudioLoopOn",
            "preAudioLoopOff",
            "preAudioAutoPlayOn",
            "preAudioAutoPlayOff",
            "AudioSource Gizmo",
            "AudioListener Icon",
            "AudioClip Icon",
            "d_preAudioLoopOff",
            "AudioSource Icon",
            "SceneViewAudio",
            
            "LockIcon-On",
            "RectTool On",
            "ToolHandleCenter",
            "curvekeyframeselected",
            "cmd right@2x",
            "Favorite",
            "SceneAsset Icon",
            "Camera Gizmo",
            "cmd left act@2x",
            "FolderEmpty Icon",
            "tab_next@2x",
            "ProfilerPaneSublabel@2x",
            "ArrowNavigationRight@2x",
            "window back@2x",
            "SceneSave",
            "pane options@2x",
            "LockIcon",
            "PackageBadgeDelete",
            "TransformTool",
            "Favorite Icon",
            "AssemblyLock",
            "cmd mid@2x",
            "CloudConnect",
            "playLoopOff",
            "tabbar on@2x",
            "UnityEditor.InspectorWindow",
            "AnimationWrapModeMenu",

            "sv_icon_name6",
            "sv_icon_name3",
            "sv_icon_name4",
            "sv_icon_name0",
            "sv_icon_name1",
            "sv_icon_name2",
            "sv_icon_name5",
            "sv_icon_name7",

            "sv_icon_dot1_sml",
            "sv_icon_dot4_sml",
            "sv_icon_dot7_sml",
            "sv_icon_dot12_sml",
            "sv_icon_dot15_sml",
            "sv_icon_dot0_sml",
            "sv_icon_dot3_sml",
            "sv_icon_dot6_sml",
            "sv_icon_dot9_sml",
            "sv_icon_dot11_sml",
            "sv_icon_dot14_sml",
            "sv_icon_dot2_sml",
            "sv_icon_dot5_sml",
            "sv_icon_dot8_sml",
            "sv_icon_dot10_sml",
            "sv_icon_dot13_sml",
            
            "sv_label_0",
            "sv_label_1",
            "sv_label_2",
            "sv_label_3",
            "sv_label_4",
            "sv_label_5",
            "sv_label_6",
            "sv_label_7",
            
            "sv_icon_dot15_pix16_gizmo",
            "sv_icon_dot5_pix16_gizmo",
            "sv_icon_dot11_pix16_gizmo",
            "sv_icon_dot9_pix16_gizmo",
            "sv_icon_dot1_pix16_gizmo",
            "sv_icon_dot8_pix16_gizmo",
            "sv_icon_dot2_pix16_gizmo",
            "sv_icon_dot6_pix16_gizmo",
            "sv_icon_dot14_pix16_gizmo",
            "sv_icon_dot7_pix16_gizmo",
            "sv_icon_dot3_pix16_gizmo",
            "sv_icon_dot0_pix16_gizmo",
            "sv_icon_dot10_pix16_gizmo",
            "sv_icon_dot12_pix16_gizmo",
            "sv_icon_dot4_pix16_gizmo",
            "sv_icon_dot13_pix16_gizmo",
            "sv_icon_none",

            "SocialNetworks.UDNOpen",
            "SocialNetworks.Tweet",
            "SocialNetworks.FacebookShare",
            "SocialNetworks.LinkedInShare",
            "SocialNetworks.UDNLogo",
            "WelcomeScreen.AssetStoreLogo",
            "UnityLogo",
            "AgeiaLogo",
            "MonoLogo",
            
            "BuildSettings.Switch.Small",
            "BuildSettings.tvOS.Small",
            "BuildSettings.Facebook.Small",
            "BuildSettings.Switch",
            "BuildSettings.tvOS",
            "BuildSettings.WebGL",
            "BuildSettings.WebGL.Small",
            "BuildSettings.Facebook",
            "BuildSettings.SelectedIcon",
            "BuildSettings.Web.Small",
            "BuildSettings.Standalone.Small",
            "BuildSettings.iPhone.Small",
            "BuildSettings.Android.Small",
            "BuildSettings.XBox360.Small",
            "BuildSettings.XboxOne.Small",
            "BuildSettings.PSP2.Small",
            "BuildSettings.PS4.Small",
            "BuildSettings.PSM.Small",
            "BuildSettings.FlashPlayer.Small",
            "BuildSettings.Metro.Small",
            "BuildSettings.WP8.Small",
            "BuildSettings.Web",
            "BuildSettings.Standalone",
            "BuildSettings.iPhone",
            "BuildSettings.Android",
            "BuildSettings.XBox360",
            "BuildSettings.XboxOne",
            "BuildSettings.PSP2",
            "BuildSettings.PS4",
            "BuildSettings.PSM",
            "BuildSettings.FlashPlayer",
            "BuildSettings.Metro",
            "BuildSettings.WP8",

            "AvatarInspector/RightFingersIk",
            "AvatarInspector/LeftFingersIk",
            "AvatarInspector/RightFeetIk",
            "AvatarInspector/LeftFeetIk",
            "AvatarInspector/MaskEditor_Root",
            "AvatarInspector/BodyPartPicker",
            "AvatarInspector/DotSelection",
            "AvatarInspector/DotFrameDotted",
            "AvatarInspector/DotFrame",
            "AvatarInspector/DotFill",
            "AvatarInspector/RightHandZoom",
            "AvatarInspector/LeftHandZoom",
            "AvatarInspector/HeadZoom",
            "AvatarInspector/RightLeg",
            "AvatarInspector/LeftLeg",
            "AvatarInspector/RightFingers",
            "AvatarInspector/RightArm",
            "AvatarInspector/LeftFingers",
            "AvatarInspector/LeftArm",
            "AvatarInspector/Head",
            "AvatarInspector/Torso",
            "AvatarInspector/RightHandZoomSilhouette",
            "AvatarInspector/LeftHandZoomSilhouette",
            "AvatarInspector/HeadZoomSilhouette",
            "AvatarInspector/BodySilhouette",
        };
        public static readonly int iconsCount = allIcons.Length;


    }

#endif
}
